TASK_TAXONOMY = ["Information Query", "State Inquiry", "Content Synthesis", "Content Transformation",
                 "Service Transaction", "System Control", "Sustained Dialogue", "Context Management"]

EVAL_PROMPT_TEMPLATE = """
You are an impartial, strict evaluator of conversational AI systems, specialized in {domain_context}.
Your job is threefold:
1. SCORE the AGENT's reply against the EXPECTED reply (primary task).
2. EXTRACT metadata about the interaction (secondary task).
3. ANALYZE pragmatic quality via Gricean Analysis Maxims (if enabled).

Follow instructions PRECISELY. Be conservative: DEFAULT to lower scores, False, or "neutral" when uncertain.

### INPUTS
USER_MESSAGE:
\"\"\"{user_input}\"\"\"

EXPECTED (reference reply):
\"\"\"{reference_text}\"\"\"

AGENT (model reply):
\"\"\"{generated_text}\"\"\"

### INSTRUCTIONS

#### A. SCORING (0-3 scale)
- Semantic Coverage: key points covered?
- Faithfulness: no contradictions/inventions?
- Appropriateness: tone/format suitable?
→ Score 0–3 (0=Poor, 3=Excellent). Ignore minor wording/punctuation. Do NOT reward verbosity.

#### B. METADATA EXTRACTION (be precise!)
- `task_type`: Infer the SINGLE most likely task from USER_MESSAGE using ONLY these categories:
{task_taxonomy}
  If none apply, use "other".
- `task_success`: Did the AGENT successfully fulfill the user's request?
  → True *only if* the reply completes the task (e.g., provides info, confirms booking, resolves issue).
  → False if: partial info, deflection, hallucination, refusal without justification, or irrelevant.
  → Default to False if uncertain.
- `user_sentiment`: Analyze ONLY the USER_MESSAGE. Choose ONE:
  "negative" (frustrated, angry, urgent),
  "neutral" (factual, inquiry),
  "positive" (happy, grateful, encouraging).
  → Default to "neutral" if uncertain.

#### C. GRICEAN ANALYSIS
Evaluate AGENT reply against Grice's Cooperative Principle.
For each maxim:
- `violated`: true/false (strict standard)
- `justification`: ≤15 words; quote evidence if possible.

Maxims:
1. Quantity: "As informative as required — no more, no less."
2. Quality: "Do not say what is false or unsupported."
3. Relation: "Be relevant to the user's goal."
4. Manner: "Be clear, brief, and orderly."

→ Default to `violated: false` ONLY if clearly adhered to.

### OUTPUT FORMAT
Return ONLY a single JSON object on one line with EXACTLY these keys:

{{
  "score": <0|1|2|3>,
  "label": "<Poor|Moderate|Good|Excellent>",
  "justification": "<1-2 sentences, ≤30 words total>",
  "evidence": {{
    "covered_points": ["<≤3 short phrases>"],
    "missing_or_wrong": ["<≤3 short phrases>"]
  }},
  "task_metadata": {{
    "task_type": "<str>",
    "task_success": <true|false>,
    "user_sentiment": "<negative|neutral|positive>"
  }},
  "gricean": {{
    "quantity": {{ "violated": <true|false>, "justification": "<≤15 words>" }},
    "quality": {{ "violated": <true|false>, "justification": "<≤15 words>" }},
    "relation": {{ "violated": <true|false>, "justification": "<≤15 words>" }},
    "manner": {{ "violated": <true|false>, "justification": "<≤15 words>" }}
  }}
}}

Do NOT include any other text, markdown, or formatting (e.g., no ```json, no comments).
"""


SUMMARIZATION_PROMPT_TEMPLATE = """
You are reviewing evaluation justifications from LLM judges about replies generated by a virtual assistant.
Interpret the context from the verdicts: (e.g., real-estate leasing, medical appointment scheduling, etc.).

Each justification contains the judge's assessment of how well the assistant's response matched the expected reply.
Your task is to **identify and summarize only the negative points**, such as:
- Errors or inaccuracies
- Misunderstandings or misinterpretations
- Missing or incomplete information
- Failure to meet expectations or requirements

**Instructions:**
- Return up to {max_bullets} concise bullet points.
- Start each point with "- " and focus on clarity and relevance.
- Avoid redundancy and prioritize actionable feedback.

---
- Judge: {judge}
- Verdicts: {verdicts}
"""
